<?php
/**
 * Test class for Dfp_Datafeed_Transfer
 * Generated by PHPUnit on 2011-12-09 at 10:59:43.
 *
 */
class Dfp_Datafeed_Transfer_Adapter_FtpTest extends PHPUnit_Framework_TestCase
{
    public function test__construct()
    {
        $passed = false;
        try {
            $sut = new Dfp_Datafeed_Transfer_Adapter_Ftp('hello');
        } catch (Dfp_Datafeed_Transfer_Adapter_Exception $e) {
            if ($e->getMessage() == 'Invalid parameter to constructor') {
                $passed  = true;
            }
        }

        $this->assertTrue($passed, 'Exception not thrown');

        $sut = new Dfp_Datafeed_Transfer_Adapter_Stream(array('basePath'=>'/var/files'));
        $this->assertEquals('/var/files', $sut->getBasePath());

        $sut = new Dfp_Datafeed_Transfer_Adapter_Stream(new Zend_Config(array('basePath'=>'/var/files')));
        $this->assertEquals('/var/files', $sut->getBasePath());

    }

    public function testSetTimeout()
    {
        $sut = new Dfp_Datafeed_Transfer_Adapter_Ftp();
        $sut->setTimeout(120, true);

        $this->assertEquals(120, $sut->getTimeout());
    }

    public function testGetTimeout()
    {
        $sut = new Dfp_Datafeed_Transfer_Adapter_Ftp();
        $this->assertEquals(90, $sut->getTimeout());
    }

    public function testSetBasePath()
    {
        $sut = new Dfp_Datafeed_Transfer_Adapter_Ftp();
        $sut->setBasePath('C:\\feedfiles\\');

        $this->assertEquals('C:\\feedfiles', $sut->getBasePath());
    }

    public function testGetBasePath()
    {
        $sut = new Dfp_Datafeed_Transfer_Adapter_Ftp();
        $this->assertNull($sut->getBasePath());
    }

    public function testSetPassive()
    {
        $sut = new Dfp_Datafeed_Transfer_Adapter_Ftp();

        $this->assertInstanceOf('Dfp_Datafeed_Transfer_Adapter_Ftp', $sut->setPassive(true));
        $this->assertTrue($sut->getPassive());
    }
    
    public function testGetPassive()
    {
    	$sut = new Dfp_Datafeed_Transfer_Adapter_Ftp();
    	
    	$this->assertFalse($sut->getPassive());    	
    }

    /**
     * @dataProvider setOptionsProvider
     */
    public function testSetOptions($var, $valid, $expected, $invalid, $message, $method)
    {
        $options[$var] = $invalid;
        $sut = new Dfp_Datafeed_Transfer_Adapter_Ftp();

        $passed = false;
        try {
            $sut->setOptions($options);
        } catch (Dfp_Datafeed_Transfer_Exception $e) {
            if ($e->getMessage = $message) {
                $passed = True;
            }
        }

        $this->assertTrue($passed, 'Exception not thrown');

        $options[$var] = $valid;

        $sut->setOptions($options);

        $this->assertEquals($expected, $sut->{'get' . $method}());
    }

    public function setOptionsProvider()
    {
    	$uri = new Dfp_Datafeed_Transfer_Uri();
    	$uri->setHost('example.com');

    	$uri2 = new Dfp_Datafeed_Transfer_Uri();
    	$uri2->setHost('example2.com');    	
    	
        return array(
            //array('schema', 'ftp', array(), 'Invalid Schema', 'Schema'),
            //array('host', 'example.com', array(), 'Invalid Host', 'Host'),
            //array('port', '2222', array(), 'Invalid Port', 'Port'),
            //array('username', 'user', array(), 'Invalid Username', 'Username'),
            //array('password', 'pass', array(), 'Invalid Password', 'Password'),
        	array('uri', array('host'=>'example.com'), $uri, 'example.com', 'Invalid value for uri option', 'Uri'),
        	array('uri', $uri2, $uri2, 'example.com', 'Invalid value for uri option', 'Uri'),
        	array('basepath', 'C:\\feedfiles', 'C:\\feedfiles', array(), 'Invalid Basepath', 'BasePath'),
        	array('passive', true, true, array('hello'), 'Invalid set passive flag, must be boolean.', 'Passive'),
        	array('timeout', '30', '30', array('hello'), 'Invalid timeout value, must be a number.', 'Timeout')
        );
    }
}